// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGrjuIVRqfWXLDhc0GB2zwrtnTVOUYSUk',
    appId: '1:1069553329112:android:695292655e8bfafa7e88ad',
    messagingSenderId: '1069553329112',
    projectId: 'kms-project-dinh',
    databaseURL: 'https://kms-project-dinh-default-rtdb.firebaseio.com',
    storageBucket: 'kms-project-dinh.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC83uHeVRvLb-V_zl3HgXwn652uWSGRZvQ',
    appId: '1:1069553329112:ios:44f86403f1ef07527e88ad',
    messagingSenderId: '1069553329112',
    projectId: 'kms-project-dinh',
    databaseURL: 'https://kms-project-dinh-default-rtdb.firebaseio.com',
    storageBucket: 'kms-project-dinh.firebasestorage.app',
    iosClientId: '1069553329112-8rf9d3oo8n81et406muov1ffuq056mbe.apps.googleusercontent.com',
    iosBundleId: 'com.nguyentan.karaoke-manage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAorgHEFfZ5MOfVxi5DFo1U42pBghUvnWI',
    appId: '1:1069553329112:web:f7cf48cdbd1dc52c7e88ad',
    messagingSenderId: '1069553329112',
    projectId: 'kms-project-dinh',
    authDomain: 'kms-project-dinh.firebaseapp.com',
    databaseURL: 'https://kms-project-dinh-default-rtdb.firebaseio.com',
    storageBucket: 'kms-project-dinh.firebasestorage.app',
    measurementId: 'G-XXQ46K1RH9',
  );
}
